-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cards
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(20) COLLATE pg_catalog."default",
    id_creator integer,
    public boolean DEFAULT false,
    image bytea,
    card bytea,
    life integer,
    damage integer,
    shield integer,
    type text COLLATE pg_catalog."default",
    CONSTRAINT cards_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uq_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.matches
(
    id integer NOT NULL,
    id_player1 integer NOT NULL,
    id_player2 integer NOT NULL,
    winner integer NOT NULL,
    CONSTRAINT matches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.deck
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    cards_id integer[] NOT NULL,
    CONSTRAINT deck_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cards
    ADD CONSTRAINT cards_id_creator_fkey FOREIGN KEY (id_creator)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.matches
    ADD CONSTRAINT id_p1 FOREIGN KEY (id_player1)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.matches
    ADD CONSTRAINT id_p2 FOREIGN KEY (id_player2)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.deck
    ADD CONSTRAINT "FK_userId" FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;